### register
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email" : "nobody@gmail.com",
    "password": "123456",
    "type" : "vendor"
}


### login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "john2@example.com",
    "password": "123456"
}



### refreshing session
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4yQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkTWF6eVZuWmFmbjFQdjZDR2wzdHFYT0pHN2V1MWVtaEkuZzNxWVh6UFpWdUIzR3FkejMwcGkiLCJ0eXBlIjoidmVuZG9yIiwiaWF0IjoxNjExMDg4MDc1LCJleHAiOjE2MTM2ODAwNzV9.49z4q0wR5nFzUhnoZtnl-XTM0oluPspYfyhkPbv-I4U

### deauthentication
POST http://localhost:3000/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4yQGV4YW1wbGUuY29tIiwidHlwZSI6InZlbmRvciIsImlhdCI6MTYxMTEwMDM5NCwiZXhwIjoxNjExMTAzMDk0fQ.X3vudbDuAGEEIpsb5YjnHjIGJRAO3tBPJNmU23cQnmc